### ISSUE TITLE
Add MongoDB

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/good-luck-api#3]
Add MongoDB to the project.
You can use this project, for example: [Example app using MongoDB](https://github.com/vercel/next.js/tree/master/examples/with-mongodb)

**Comment by fuadnafiz98** [comment]
Hi @RuanAragao, I want to work on this issue. 
Could you please assign me the issue

**Comment by RuanAragao** [comment]
> Hi @RuanAragao, I want to work on this issue. Could you please assign me the issue

At first, just prepare the project to use MongoDB.
Install the packages and configure the database connection.

**Comment by fuadnafiz98** [comment]
Can I use [prisma](https://www.prisma.io/) to connect to the database?

**Comment by RuanAragao** [comment]
@fuadnafiz98 yes, you can!

**Comment by fuadnafiz98** [comment]
I have made the pull request. Would you please review the code?
