### ISSUE TITLE
Implement random number on API

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/good-luck-api#8]
We have a random number generator ([pages/api/utils/random-number.ts](https://github.com/RuanAragao/good-luck-api/blob/main/pages/api/utils/random-number.ts)) and we need to return a value from it in endpoint `/api/number` ([/pages/api/number.ts](https://github.com/RuanAragao/good-luck-api/blob/main/pages/api/number.ts)).

The number must be 8 digits.

Eg: 
```json
{
  "number": "00103178"
}
```

**Comment by Raghav-Modani** [comment]
I can give it  a shot. Please assign this to me.

**Comment by RuanAragao** [comment]
> I have a doubt. I am using the dynamic API routes. How are we going to navigate to the API route? I mean are we going to use a button to link to the API URL and passing the random number to the URL?

You can use an API cliente for your tests, I use [Insomnia](https://insomnia.rest/).
The API will be used, firstment, in the [Good Luck Android App](https://github.com/RuanAragao/good-luck-android-app)

Solved? Or I confused your doubt?
